### ISSUE TITLE
Python 2 compatibility needed

### ISSUE THREAD

**Issue by austinkbarry** [codex-team/html-slacker#4]
Not python 2 compatible.  Added the following to make it work..

try:
    from html.parser import HTMLParser
    from html.entities import name2codepoint
except:
    from HTMLParser import HTMLParser
    from htmlentitydefs import name2codepoint

**Comment by n0str** [comment]
@austinkbarry, thank you for the comment. We appreciate reports about actual bugs.

Our code is really not Python2 compatible as mentioned in https://github.com/codex-team/html-slacker/issues/2

If you have time, it would be amazing to get a pull request with your fix, otherwise, we'll try to fix this issue soon.
